interface Verb {
    number: number;
    verb: string;
    pastSimple: string;
    pastParticiple: string;
    presentParticiple: string;
    hindiMeaning: string;
    example: string;
  }
  
  export const verbs: Verb[] = [
    {
      number: 1,
      verb: "Sleep (स्लीप)",
      pastSimple: "Slept (स्लेप्ट)",
      pastParticiple: "Slept (स्लेप्ट)",
      presentParticiple: "Sleeping (स्लीपिंग)",
      hindiMeaning: "सोना (Sona)",
      example: "I sleep every night. (मैं हर रात सोता हूँ।)",
    },
    {
      number: 2,
      verb: "Go (गो)",
      pastSimple: "Went (वेंट)",
      pastParticiple: "Gone (गॉन)",
      presentParticiple: "Going (गोइंग)",
      hindiMeaning: "जाना (Jana)",
      example: "She goes to the market. (वह बाजार जाती है।)",
    },
    {
      number: 3,
      verb: "Eat (ईट)",
      pastSimple: "Ate (एट)",
      pastParticiple: "Eaten (ईटन)",
      presentParticiple: "Eating (ईटिंग)",
      hindiMeaning: "खाना (Khana)",
      example: "They are eating lunch. (वे दोपहर का खाना खा रहे हैं।)",
    },
    {
      number: 4,
      verb: "Write (राइट)",
      pastSimple: "Wrote (रोट)",
      pastParticiple: "Written (रिटन)",
      presentParticiple: "Writing (राइटिंग)",
      hindiMeaning: "लिखना (Likhna)",
      example: "He writes a letter. (वह पत्र लिखता है।)",
    },
    {
      number: 5,
      verb: "Run (रन)",
      pastSimple: "Ran (रैन)",
      pastParticiple: "Run (रन)",
      presentParticiple: "Running (रनिंग)",
      hindiMeaning: "दौड़ना (Daudna)",
      example: "I run every morning. (मैं हर सुबह दौड़ता हूँ।)",
    },
    {
      number: 6,
      verb: "Speak (स्पीक)",
      pastSimple: "Spoke (स्पोक)",
      pastParticiple: "Spoken (स्पोकन)",
      presentParticiple: "Speaking (स्पीकिंग)",
      hindiMeaning: "बोलना (Bolna)",
      example: "She speaks English. (वह अंग्रेजी बोलती है।)",
    },
    {
      number: 7,
      verb: "Read (रीड)",
      pastSimple: "Read (रीड)",
      pastParticiple: "Read (रीड)",
      presentParticiple: "Reading (रीडिंग)",
      hindiMeaning: "पढ़ना (Padhna)",
      example: "I read a book. (मैं किताब पढ़ता हूँ।)",
    },
    {
      number: 8,
      verb: "Take (टेक)",
      pastSimple: "Took (टुक)",
      pastParticiple: "Taken (टेकन)",
      presentParticiple: "Taking (टेकिंग)",
      hindiMeaning: "लेना (Lena)",
      example: "He took my book. (उसने मेरी किताब ली।)",
    },
    {
      number: 9,
      verb: "Give (गिव)",
      pastSimple: "Gave (गेव)",
      pastParticiple: "Given (गिवन)",
      presentParticiple: "Giving (गिविंग)",
      hindiMeaning: "देना (Dena)",
      example: "I give him advice. (मैं उसे सलाह देता हूँ।)",
    },
    {
      number: 10,
      verb: "Play (प्ले)",
      pastSimple: "Played (प्लेड़)",
      pastParticiple: "Played (प्लेड़)",
      presentParticiple: "Playing (प्लेइंग)",
      hindiMeaning: "खेलना (Khelna)",
      example: "They are playing football. (वे फुटबॉल खेल रहे हैं।)",
    },
    {
      number: 11,
      verb: "Sit (सिट)",
      pastSimple: "Sat (सैट)",
      pastParticiple: "Sat (सैट)",
      presentParticiple: "Sitting (सिटिंग)",
      hindiMeaning: "बैठना (Baithna)",
      example: "He sits on the chair. (वह कुर्सी पर बैठता है।)",
    },
    {
      number: 12,
      verb: "Stand (स्टैंड)",
      pastSimple: "Stood (स्टुड)",
      pastParticiple: "Stood (स्टुड)",
      presentParticiple: "Standing (स्टैंडिंग)",
      hindiMeaning: "खड़ा होना (Khada Hona)",
      example: "She is standing outside. (वह बाहर खड़ी है।)",
    },
    {
      number: 13,
      verb: "Walk (वॉक)",
      pastSimple: "Walked (वॉक्ट)",
      pastParticiple: "Walked (वॉक्ट)",
      presentParticiple: "Walking (वॉकिंग)",
      hindiMeaning: "चलना (Chalna)",
      example: "I walk to school. (मैं स्कूल तक चलता हूँ।)",
    },
    {
      number: 14,
      verb: "Talk (टॉक)",
      pastSimple: "Talked (टॉक्ड)",
      pastParticiple: "Talked (टॉक्ड)",
      presentParticiple: "Talking (टॉकिंग)",
      hindiMeaning: "बात करना (Baat Karna)",
      example: "They are talking. (वे बात कर रहे हैं।)",
    },
    {
      number: 15,
      verb: "Drink (ड्रिंक)",
      pastSimple: "Drank (ड्रैंक)",
      pastParticiple: "Drunk (ड्रंक)",
      presentParticiple: "Drinking (ड्रिंकिंग)",
      hindiMeaning: "पीना (Pina)",
      example: "He drank water. (उसने पानी पिया।)",
    },
    {
      number: 16,
      verb: "See (सी)",
      pastSimple: "Saw (सा)",
      pastParticiple: "Seen (सीन)",
      presentParticiple: "Seeing (सीइंग)",
      hindiMeaning: "देखना (Dekhna)",
      example: "I see the stars. (मैं सितारों को देखता हूँ।)",
    },
    {
      number: 17,
      verb: "Buy (बाय)",
      pastSimple: "Bought (बॉट)",
      pastParticiple: "Bought (बॉट)",
      presentParticiple: "Buying (बाइइंग)",
      hindiMeaning: "खरीदना (Kharidna)",
      example: "She buys vegetables. (वह सब्जियां खरीदती है।)",
    },
    {
      number: 18,
      verb: "Sell (सेल)",
      pastSimple: "Sold (सोल्ड)",
      pastParticiple: "Sold (सोल्ड)",
      presentParticiple: "Selling (सेलिंग)",
      hindiMeaning: "बेचना (Bechna)",
      example: "He sold his bike. (उसने अपनी बाइक बेची।)",
    },
    {
      number: 19,
      verb: "Begin (बिगिन)",
      pastSimple: "Began (बिगैन)",
      pastParticiple: "Begun (बिगन)",
      presentParticiple: "Beginning (बिगिनिंग)",
      hindiMeaning: "शुरू करना (Shuru Karna)",
      example: "The meeting began late. (बैठक देर से शुरू हुई।)",
    },
    {
      number: 20,
      verb: "Feel (फील)",
      pastSimple: "Felt (फेल्ट)",
      pastParticiple: "Felt (फेल्ट)",
      presentParticiple: "Feeling (फीलिंग)",
      hindiMeaning: "महसूस करना (Mehsoos Karna)",
      example: "I feel happy. (मैं खुश महसूस करता हूँ।)",
    },
    {
      number: 21,
      verb: "Come (कम)",
      pastSimple: "Came (केम)",
      pastParticiple: "Come (कम)",
      presentParticiple: "Coming (कमिंग)",
      hindiMeaning: "आना (Aana)",
      example: "He comes home late. (वह घर देर से आता है।)",
    },
    {
      number: 22,
      verb: "Leave (लीव)",
      pastSimple: "Left (लेफ्ट)",
      pastParticiple: "Left (लेफ्ट)",
      presentParticiple: "Leaving (लीविंग)",
      hindiMeaning: "छोड़ना (Chhodna)",
      example: "She left early. (वह जल्दी चली गई।)",
    },
    {
      number: 23,
      verb: "Build (बिल्ड)",
      pastSimple: "Built (बिल्ट)",
      pastParticiple: "Built (बिल्ट)",
      presentParticiple: "Building (बिल्डिंग)",
      hindiMeaning: "निर्माण करना (Nirman Karna)",
      example: "They are building a house. (वे एक घर बना रहे हैं।)",
    },
    {
      number: 24,
      verb: "Break (ब्रेक)",
      pastSimple: "Broke (ब्रोके)",
      pastParticiple: "Broken (ब्रोकेन)",
      presentParticiple: "Breaking (ब्रेकिंग)",
      hindiMeaning: "तोड़ना (Todna)",
      example: "He broke the glass. (उसने गिलास तोड़ दिया।)",
    },
    {
      number: 25,
      verb: "Bring (ब्रिंग)",
      pastSimple: "Brought (ब्रॉट)",
      pastParticiple: "Brought (ब्रॉट)",
      presentParticiple: "Bringing (ब्रिंगिंग)",
      hindiMeaning: "लाना (Lana)",
      example: "She brings flowers. (वह फूल लाती है।)",
    },
    {
      number: 26,
      verb: "Catch (कैच)",
      pastSimple: "Caught (कॉट)",
      pastParticiple: "Caught (कॉट)",
      presentParticiple: "Catching (कैचिंग)",
      hindiMeaning: "पकड़ना (Pakadna)",
      example: "He caught the ball. (उसने गेंद पकड़ी।)",
    },
    {
      number: 27,
      verb: "Choose (चूज़)",
      pastSimple: "Chose (चोज)",
      pastParticiple: "Chosen (चोजन)",
      presentParticiple: "Choosing (चूज़िंग)",
      hindiMeaning: "चुनना (Chunna)",
      example: "I chose a red dress. (मैंने एक लाल ड्रेस चुनी।)",
    },
    {
      number: 28,
      verb: "Cut (कट)",
      pastSimple: "Cut (कट)",
      pastParticiple: "Cut (कट)",
      presentParticiple: "Cutting (कटिंग)",
      hindiMeaning: "काटना (Kaatna)",
      example: "He cuts paper. (वह कागज काटता है।)",
    },
    {
      number: 29,
      verb: "Do (डू)",
      pastSimple: "Did (डिड)",
      pastParticiple: "Done (डन)",
      presentParticiple: "Doing (डूइंग)",
      hindiMeaning: "करना (Karna)",
      example: "I did my homework. (मैंने अपना होमवर्क किया।)",
    },
    {
      number: 30,
      verb: "Draw (ड्रॉ)",
      pastSimple: "Drew (ड्रू)",
      pastParticiple: "Drawn (ड्रॉन)",
      presentParticiple: "Drawing (ड्रॉइंग)",
      hindiMeaning: "खींचना/चित्र बनाना (Kheenchna/Chitra Banana)",
      example: "She draws beautiful pictures. (वह सुंदर चित्र बनाती है।)",
    },
    {
      number: 31,
      verb: "Fall (फॉल)",
      pastSimple: "Fell (फेल)",
      pastParticiple: "Fallen (फॉलन)",
      presentParticiple: "Falling (फॉलिंग)",
      hindiMeaning: "गिरना (Girna)",
      example: "He fell from the tree. (वह पेड़ से गिर गया।)",
    },
    {
      number: 32,
      verb: "Fight (फाइट)",
      pastSimple: "Fought (फॉट)",
      pastParticiple: "Fought (फॉट)",
      presentParticiple: "Fighting (फाइटिंग)",
      hindiMeaning: "लड़ना (Ladna)",
      example: "They fought bravely. (उन्होंने बहादुरी से लड़ाई लड़ी।)",
    },
    {
      number: 33,
      verb: "Find (फाइंड)",
      pastSimple: "Found (फाउंड)",
      pastParticiple: "Found (फाउंड)",
      presentParticiple: "Finding (फाइंडिंग)",
      hindiMeaning: "खोजना (Khojna)",
      example: "I found my keys. (मुझे मेरी चाबियां मिल गईं।)",
    },
    {
      number: 34,
      verb: "Fly (फ्लाइ)",
      pastSimple: "Flew (फ्लू)",
      pastParticiple: "Flown (फ्लोन)",
      presentParticiple: "Flying (फ्लाइंग)",
      hindiMeaning: "उड़ना (Udna)",
      example: "Birds fly in the sky. (पक्षी आसमान में उड़ते हैं।)",
    },
    {
      number: 35,
      verb: "Forget (फॉरगेट)",
      pastSimple: "Forgot (फॉरगॉट)",
      pastParticiple: "Forgotten (फॉरगॉटन)",
      presentParticiple: "Forgetting (फॉरगेटिंग)",
      hindiMeaning: "भूलना (Bhoolna)",
      example: "I forgot her name. (मैं उसका नाम भूल गया।)",
    },
    {
      number: 36,
      verb: "Give (गिव)",
      pastSimple: "Gave (गेव)",
      pastParticiple: "Given (गिवन)",
      presentParticiple: "Giving (गिविंग)",
      hindiMeaning: "देना (Dena)",
      example: "He gave me a gift. (उसने मुझे एक तोहफा दिया।)",
    },
    {
      number: 37,
      verb: "Hear (हियर)",
      pastSimple: "Heard (हर्ड)",
      pastParticiple: "Heard (हर्ड)",
      presentParticiple: "Hearing (हियरिंग)",
      hindiMeaning: "सुनना (Sunna)",
      example: "I heard the news. (मैंने खबर सुनी।)",
    },
    {
      number: 38,
      verb: "Hide (हाइड)",
      pastSimple: "Hid (हिड)",
      pastParticiple: "Hidden (हिडन)",
      presentParticiple: "Hiding (हाइडिंग)",
      hindiMeaning: "छिपाना (Chhupana)",
      example: "He is hiding behind the door. (वह दरवाजे के पीछे छिपा है।)",
    },
    {
      number: 39,
      verb: "Hold (होल्ड)",
      pastSimple: "Held (हेल्ड)",
      pastParticiple: "Held (हेल्ड)",
      presentParticiple: "Holding (होल्डिंग)",
      hindiMeaning: "पकड़ना (Pakadna)",
      example: "She holds my hand. (वह मेरा हाथ पकड़ती है।)",
    },
    {
      number: 40,
      verb: "Keep (कीप)",
      pastSimple: "Kept (केप्ट)",
      pastParticiple: "Kept (केप्ट)",
      presentParticiple: "Keeping (कीपिंग)",
      hindiMeaning: "रखना (Rakhna)",
      example: "He keeps his room clean. (वह अपने कमरे को साफ रखता है।)",
    },
    {
      number: 41,
      verb: "Know (नो)",
      pastSimple: "Knew (न्यू)",
      pastParticiple: "Known (नोन)",
      presentParticiple: "Knowing (नोइंग)",
      hindiMeaning: "जानना (Janna)",
      example: "I know the answer. (मैं उत्तर जानता हूँ।)",
    },
    {
      number: 42,
      verb: "Learn (लर्न)",
      pastSimple: "Learned (लर्न्ड)",
      pastParticiple: "Learned (लर्न्ड)",
      presentParticiple: "Learning (लर्निंग)",
      hindiMeaning: "सीखना (Seekhna)",
      example: "She is learning French. (वह फ्रेंच सीख रही है।)",
    },
    {
      number: 43,
      verb: "Lose (लूज़)",
      pastSimple: "Lost (लॉस्ट)",
      pastParticiple: "Lost (लॉस्ट)",
      presentParticiple: "Losing (लूज़िंग)",
      hindiMeaning: "खोना (Khona)",
      example: "I lost my wallet. (मैंने अपना बटुआ खो दिया।)",
    },
    {
      number: 44,
      verb: "Make (मेक)",
      pastSimple: "Made (मेड)",
      pastParticiple: "Made (मेड)",
      presentParticiple: "Making (मेकिंग)",
      hindiMeaning: "बनाना (Banana)",
      example: "He is making tea. (वह चाय बना रहा है।)",
    },
    {
      number: 45,
      verb: "Meet (मीट)",
      pastSimple: "Met (मेट)",
      pastParticiple: "Met (मेट)",
      presentParticiple: "Meeting (मीटिंग)",
      hindiMeaning: "मिलना (Milna)",
      example: "I met him yesterday. (मैं उससे कल मिला।)",
    },
    {
      number: 46,
      verb: "Open (ओपन)",
      pastSimple: "Opened (ओपन्ड)",
      pastParticiple: "Opened (ओपन्ड)",
      presentParticiple: "Opening (ओपनिंग)",
      hindiMeaning: "खोलना (Kholna)",
      example: "He opened the door. (उसने दरवाजा खोला।)",
    },
    {
      number: 47,
      verb: "Put (पुट)",
      pastSimple: "Put (पुट)",
      pastParticiple: "Put (पुट)",
      presentParticiple: "Putting (पुटिंग)",
      hindiMeaning: "रखना (Rakhna)",
      example: "She put the book on the table. (उसने किताब को मेज पर रखा।)",
    },
    {
      number: 48,
      verb: "Read (रीड)",
      pastSimple: "Read (रेड)",
      pastParticiple: "Read (रेड)",
      presentParticiple: "Reading (रीडिंग)",
      hindiMeaning: "पढ़ना (Padhna)",
      example: "I read a novel yesterday. (मैंने कल एक उपन्यास पढ़ा।)",
    },
    {
      number: 49,
      verb: "Ride (राइड)",
      pastSimple: "Rode (रोड)",
      pastParticiple: "Ridden (रिडन)",
      presentParticiple: "Riding (राइडिंग)",
      hindiMeaning: "सवारी करना (Sawari Karna)",
      example: "He is riding a bicycle. (वह साइकिल चला रहा है।)",
    },
    {
      number: 50,
      verb: "Rise (राइज)",
      pastSimple: "Rose (रोज)",
      pastParticiple: "Risen (रिजन)",
      presentParticiple: "Rising (राइजिंग)",
      hindiMeaning: "उठना (Uthna)",
      example: "The sun rises in the east. (सूरज पूर्व में उगता है।)",
    },
    {
      number: 51,
      verb: "Run (रन)",
      pastSimple: "Ran (रैन)",
      pastParticiple: "Run (रन)",
      presentParticiple: "Running (रनिंग)",
      hindiMeaning: "दौड़ना (Daudna)",
      example: "He is running fast. (वह तेज दौड़ रहा है।)",
    },
    {
      number: 52,
      verb: "Say (से)",
      pastSimple: "Said (सेड)",
      pastParticiple: "Said (सेड)",
      presentParticiple: "Saying (सेइंग)",
      hindiMeaning: "कहना (Kehna)",
      example: "She said hello. (उसने हैलो कहा।)",
    },
    {
      number: 53,
      verb: "See (सी)",
      pastSimple: "Saw (सॉ)",
      pastParticiple: "Seen (सीन)",
      presentParticiple: "Seeing (सीइंग)",
      hindiMeaning: "देखना (Dekhna)",
      example: "I saw a movie yesterday. (मैंने कल एक फिल्म देखी।)",
    },
    {
      number: 54,
      verb: "Send (सेंड)",
      pastSimple: "Sent (सेंट)",
      pastParticiple: "Sent (सेंट)",
      presentParticiple: "Sending (सेंडिंग)",
      hindiMeaning: "भेजना (Bhejna)",
      example: "He sent a letter. (उसने एक पत्र भेजा।)",
    },
    {
      number: 55,
      verb: "Sing (सिंग)",
      pastSimple: "Sang (सैंग)",
      pastParticiple: "Sung (संग)",
      presentParticiple: "Singing (सिंगिंग)",
      hindiMeaning: "गाना (Gana)",
      example: "She is singing a song. (वह एक गाना गा रही है।)",
    },
    {
      number: 56,
      verb: "Sit (सिट)",
      pastSimple: "Sat (सैट)",
      pastParticiple: "Sat (सैट)",
      presentParticiple: "Sitting (सिटिंग)",
      hindiMeaning: "बैठना (Baithna)",
      example: "I sat on the bench. (मैं बेंच पर बैठा।)",
    },
    {
      number: 57,
      verb: "Sleep (स्लीप)",
      pastSimple: "Slept (स्लेप्ट)",
      pastParticiple: "Slept (स्लेप्ट)",
      presentParticiple: "Sleeping (स्लीपिंग)",
      hindiMeaning: "सोना (Sona)",
      example: "He slept early. (वह जल्दी सो गया।)",
    },
    {
      number: 58,
      verb: "Speak (स्पीक)",
      pastSimple: "Spoke (स्पोक)",
      pastParticiple: "Spoken (स्पोकन)",
      presentParticiple: "Speaking (स्पीकिंग)",
      hindiMeaning: "बोलना (Bolna)",
      example: "She speaks clearly. (वह स्पष्ट बोलती है।)",
    },
    {
      number: 59,
      verb: "Stand (स्टैंड)",
      pastSimple: "Stood (स्टुड)",
      pastParticiple: "Stood (स्टुड)",
      presentParticiple: "Standing (स्टैंडिंग)",
      hindiMeaning: "खड़ा होना (Khada Hona)",
      example: "He stood near the window. (वह खिड़की के पास खड़ा था।)",
    },
    {
      number: 60,
      verb: "Start (स्टार्ट)",
      pastSimple: "Started (स्टार्टेड)",
      pastParticiple: "Started (स्टार्टेड)",
      presentParticiple: "Starting (स्टार्टिंग)",
      hindiMeaning: "शुरू करना (Shuru Karna)",
      example: "They started the project. (उन्होंने परियोजना शुरू की।)",
    },
    {
      number: 61,
      verb: "Stop (स्टॉप)",
      pastSimple: "Stopped (स्टॉप्ड)",
      pastParticiple: "Stopped (स्टॉप्ड)",
      presentParticiple: "Stopping (स्टॉपिंग)",
      hindiMeaning: "रोकना (Rokna)",
      example: "Please stop talking. (कृपया बात करना बंद करें।)",
    },
    {
      number: 62,
      verb: "Take (टेक)",
      pastSimple: "Took (टुक)",
      pastParticiple: "Taken (टेकिन)",
      presentParticiple: "Taking (टेकिंग)",
      hindiMeaning: "लेना (Lena)",
      example: "She took the book. (उसने किताब ली।)",
    },
    {
      number: 63,
      verb: "Talk (टॉक)",
      pastSimple: "Talked (टॉक्ड)",
      pastParticiple: "Talked (टॉक्ड)",
      presentParticiple: "Talking (टॉकिंग)",
      hindiMeaning: "बात करना (Baat Karna)",
      example: "They are talking loudly. (वे जोर से बात कर रहे हैं।)",
    },
    {
      number: 64,
      verb: "Think (थिंक)",
      pastSimple: "Thought (थॉट)",
      pastParticiple: "Thought (थॉट)",
      presentParticiple: "Thinking (थिंकिंग)",
      hindiMeaning: "सोचना (Sochna)",
      example: "I think she is right. (मैं सोचता हूँ कि वह सही है।)",
    },
    {
      number: 65,
      verb: "Throw (थ्रो)",
      pastSimple: "Threw (थ्रू)",
      pastParticiple: "Thrown (थ्रोन)",
      presentParticiple: "Throwing (थ्रोइंग)",
      hindiMeaning: "फेंकना (Fekna)",
      example: "He threw the ball. (उसने गेंद फेंकी।)",
    },
    {
      number: 66,
      verb: "Understand (अंडरस्टैंड)",
      pastSimple: "Understood (अंडरस्टुड)",
      pastParticiple: "Understood (अंडरस्टुड)",
      presentParticiple: "Understanding (अंडरस्टैंडिंग)",
      hindiMeaning: "समझना (Samajhna)",
      example: "I understand your point. (मैं आपका बिंदु समझता हूँ।)",
    },
    {
      number: 67,
      verb: "Visit (विजिट)",
      pastSimple: "Visited (विजिटेड)",
      pastParticiple: "Visited (विजिटेड)",
      presentParticiple: "Visiting (विजिटिंग)",
      hindiMeaning: "यात्रा करना (Yatra Karna)",
      example: "They visited the museum. (उन्होंने संग्रहालय का दौरा किया।)",
    },
    {
      number: 68,
      verb: "Wait (वेट)",
      pastSimple: "Waited (वेटेड)",
      pastParticiple: "Waited (वेटेड)",
      presentParticiple: "Waiting (वेटिंग)",
      hindiMeaning: "इंतजार करना (Intezaar Karna)",
      example: "We waited for the bus. (हमने बस का इंतजार किया।)",
    },
    {
      number: 69,
      verb: "Walk (वॉक)",
      pastSimple: "Walked (वॉक्ड)",
      pastParticiple: "Walked (वॉक्ड)",
      presentParticiple: "Walking (वॉकिंग)",
      hindiMeaning: "चलना (Chalna)",
      example: "He walks to school every day. (वह हर दिन स्कूल पैदल जाता है।)",
    },
    {
      number: 70,
      verb: "Want (वांट)",
      pastSimple: "Wanted (वांटेड)",
      pastParticiple: "Wanted (वांटेड)",
      presentParticiple: "Wanting (वांटिंग)",
      hindiMeaning: "चाहना (Chahna)",
      example: "I want to go home. (मैं घर जाना चाहता हूँ।)",
    },
    {
      number: 71,
      verb: "Win (विन)",
      pastSimple: "Won (वॉन)",
      pastParticiple: "Won (वॉन)",
      presentParticiple: "Winning (विनिंग)",
      hindiMeaning: "जीतना (Jeetna)",
      example: "They won the match. (उन्होंने मैच जीता।)",
    },
    {
      number: 72,
      verb: "Work (वर्क)",
      pastSimple: "Worked (वर्क्ड)",
      pastParticiple: "Worked (वर्क्ड)",
      presentParticiple: "Working (वर्किंग)",
      hindiMeaning: "काम करना (Kaam Karna)",
      example: "She works in a bank. (वह एक बैंक में काम करती है।)",
    },
    {
      number: 73,
      verb: "Write (राइट)",
      pastSimple: "Wrote (रोट)",
      pastParticiple: "Written (रिटन)",
      presentParticiple: "Writing (राइटिंग)",
      hindiMeaning: "लिखना (Likhna)",
      example: "He writes letters every day. (वह हर दिन पत्र लिखता है।)",
    },
    {
      number: 74,
      verb: "Ask (आस्क)",
      pastSimple: "Asked (आस्क्ड)",
      pastParticiple: "Asked (आस्क्ड)",
      presentParticiple: "Asking (आस्किंग)",
      hindiMeaning: "पूछना (Poochna)",
      example: "She asked a question. (उसने एक सवाल पूछा।)",
    },
    {
      number: 75,
      verb: "Answer (आंसर)",
      pastSimple: "Answered (आंसरड)",
      pastParticiple: "Answered (आंसरड)",
      presentParticiple: "Answering (आंसरिंग)",
      hindiMeaning: "उत्तर देना (Uttar Dena)",
      example: "He answered my question. (उसने मेरा सवाल उत्तर दिया।)",
    },
    {
      number: 76,
      verb: "Borrow (बॉरो)",
      pastSimple: "Borrowed (बॉरोड)",
      pastParticiple: "Borrowed (बॉरोड)",
      presentParticiple: "Borrowing (बॉरिंग)",
      hindiMeaning: "उधार लेना (Udhaar Lena)",
      example: "She borrowed a pen from me. (उसने मुझसे एक पेन उधार लिया।)",
    },
    {
      number: 77,
      verb: "Build (बिल्ड)",
      pastSimple: "Built (बिल्ट)",
      pastParticiple: "Built (बिल्ट)",
      presentParticiple: "Building (बिल्डिंग)",
      hindiMeaning: "बनाना (Banana)",
      example: "They are building a new house. (वे एक नया घर बना रहे हैं।)",
    },
    {
      number: 78,
      verb: "Buy (बाई)",
      pastSimple: "Bought (बॉट)",
      pastParticiple: "Bought (बॉट)",
      presentParticiple: "Buying (बाइइंग)",
      hindiMeaning: "खरीदना (Kharidna)",
      example: "I bought a new phone. (मैंने एक नया फोन खरीदा।)",
    },
    {
      number: 79,
      verb: "Cancel (कैंसल)",
      pastSimple: "Cancelled (कैंसिल्ड)",
      pastParticiple: "Cancelled (कैंसिल्ड)",
      presentParticiple: "Cancelling (कैंसिलिंग)",
      hindiMeaning: "रद्द करना (Radd Karna)",
      example: "They cancelled the meeting. (उन्होंने बैठक रद्द कर दी।)",
    },
    {
      number: 80,
      verb: "Celebrate (सेलेब्रेट)",
      pastSimple: "Celebrated (सेलेब्रेटेड)",
      pastParticiple: "Celebrated (सेलेब्रेटेड)",
      presentParticiple: "Celebrating (सेलेब्रेटिंग)",
      hindiMeaning: "मनाना (Manana)",
      example:
        "They celebrate Christmas every year. (वे हर साल क्रिसमस मनाते हैं।)",
    },
    {
      number: 81,
      verb: "Change (चेंज)",
      pastSimple: "Changed (चेंज्ड)",
      pastParticiple: "Changed (चेंज्ड)",
      presentParticiple: "Changing (चेंजिंग)",
      hindiMeaning: "बदलना (Badalna)",
      example: "She changed her clothes. (उसने अपने कपड़े बदले।)"
    },
    {
      number: 82,
      verb: "Clean (क्लीन)",
      pastSimple: "Cleaned (क्लीनड)",
      pastParticiple: "Cleaned (क्लीनड)",
      presentParticiple: "Cleaning (क्लीनिंग)",
      hindiMeaning: "साफ करना (Saaf Karna)",
      example: "I cleaned my room. (मैंने अपना कमरा साफ किया।)"
    },
    {
      number: 83,
      verb: "Close (क्लोज)",
      pastSimple: "Closed (क्लोज्ड)",
      pastParticiple: "Closed (क्लोज्ड)",
      presentParticiple: "Closing (क्लोजिंग)",
      hindiMeaning: "बंद करना (Band Karna)",
      example: "Please close the door. (कृपया दरवाजा बंद करें।)"
    },
    {
      number: 84,
      verb: "Cook (कुक)",
      pastSimple: "Cooked (कुकीड)",
      pastParticiple: "Cooked (कुकीड)",
      presentParticiple: "Cooking (कुकिंग)",
      hindiMeaning: "पकाना (Pakana)",
      example: "She is cooking dinner. (वह रात का खाना बना रही है।)"
    },
    {
      number: 85,
      verb: "Dance (डांस)",
      pastSimple: "Danced (डांसड)",
      pastParticiple: "Danced (डांसड)",
      presentParticiple: "Dancing (डांसिंग)",
      hindiMeaning: "नृत्य करना (Nritya Karna)",
      example: "They are dancing at the party. (वे पार्टी में नृत्य कर रहे हैं।)"
    },
    {
      number: 86,
      verb: "Deliver (डिलिवर)",
      pastSimple: "Delivered (डिलिवर्ड)",
      pastParticiple: "Delivered (डिलिवर्ड)",
      presentParticiple: "Delivering (डिलिवरिंग)",
      hindiMeaning: "प्रसार करना (Prasar Karna)",
      example: "The mailman delivered the letter. (मेलमैन ने पत्र पहुंचाया।)"
    },
    {
      number: 87,
      verb: "Describe (डिस्क्राइब)",
      pastSimple: "Described (डिस्क्राइब्ड)",
      pastParticiple: "Described (डिस्क्राइब्ड)",
      presentParticiple: "Describing (डिस्क्राइबिंग)",
      hindiMeaning: "वर्णन करना (Varnan Karna)",
      example: "Can you describe the picture? (क्या आप चित्र का वर्णन कर सकते हैं?)"
    },
    {
      number: 88,
      verb: "Draw (ड्रॉ)",
      pastSimple: "Drew (ड्रू)",
      pastParticiple: "Drawn (ड्रॉन)",
      presentParticiple: "Drawing (ड्रॉइंग)",
      hindiMeaning: "चित्र बनाना (Chitra Banana)",
      example: "He draws beautiful pictures. (वह सुंदर चित्र बनाता है।)"
    },
    {
      number: 89,
      verb: "Dream (ड्रीम)",
      pastSimple: "Dreamed (ड्रीम्ड)",
      pastParticiple: "Dreamed (ड्रीम्ड)",
      presentParticiple: "Dreaming (ड्रीमिंग)",
      hindiMeaning: "सपना देखना (Sapna Dekhna)",
      example: "I dreamed of traveling to Paris. (मैंने पेरिस यात्रा करने का सपना देखा।)"
    },
    {
      number: 90,
      verb: "Drive (ड्राइव)",
      pastSimple: "Drove (ड्रोक)",
      pastParticiple: "Driven (ड्रिवन)",
      presentParticiple: "Driving (ड्राइविंग)",
      hindiMeaning: "गाड़ी चलाना (Gaadi Chalana)",
      example: "He is driving to work. (वह काम पर जा रहा है।)"
    },
    {
      number: 91,
      verb: "Eat (ईट)",
      pastSimple: "Ate (एट)",
      pastParticiple: "Eaten (ईटन)",
      presentParticiple: "Eating (ईटिंग)",
      hindiMeaning: "खाना (Khana)",
      example: "I ate lunch at noon. (मैंने दोपहर में लंच खाया।)"
    },
    {
      number: 92,
      verb: "Enjoy (एन्जॉय)",
      pastSimple: "Enjoyed (एन्जॉयड)",
      pastParticiple: "Enjoyed (एन्जॉयड)",
      presentParticiple: "Enjoying (एन्जॉयइंग)",
      hindiMeaning: "आनंद लेना (Anand Lena)",
      example: "They are enjoying the party. (वे पार्टी का आनंद ले रहे हैं।)"
    },
    {
      number: 93,
      verb: "Enter (एंटर)",
      pastSimple: "Entered (एंटरड)",
      pastParticiple: "Entered (एंटरड)",
      presentParticiple: "Entering (एंटरिंग)",
      hindiMeaning: "प्रवेश करना (Pravesh Karna)",
      example: "Please enter the room. (कृपया कमरे में प्रवेश करें।)"
    },
    {
      number: 94,
      verb: "Explain (एक्सप्लेन)",
      pastSimple: "Explained (एक्सप्लेंड)",
      pastParticiple: "Explained (एक्सप्लेंड)",
      presentParticiple: "Explaining (एक्सप्लेनिंग)",
      hindiMeaning: "व्याख्या करना (Vyakhya Karna)",
      example: "Can you explain the answer? (क्या आप उत्तर समझा सकते हैं?)"
    },
    {
      number: 95,
      verb: "Fall (फॉल)",
      pastSimple: "Fell (फेल)",
      pastParticiple: "Fallen (फालन)",
      presentParticiple: "Falling (फॉलिंग)",
      hindiMeaning: "गिरना (Girna)",
      example: "She fell off the ladder. (वह सीढ़ी से गिर गई।)"
    },
    {
      number: 96,
      verb: "Fasten (फास्टन)",
      pastSimple: "Fastened (फास्टनड)",
      pastParticiple: "Fastened (फास्टनड)",
      presentParticiple: "Fastening (फास्टनिंग)",
      hindiMeaning: "बंधना (Bandhna)",
      example: "Please fasten your seatbelt. (कृपया अपनी सीट बेल्ट बांधें।)"
    },
    {
      number: 97,
      verb: "Find (फाइंड)",
      pastSimple: "Found (फाउंड)",
      pastParticiple: "Found (फाउंड)",
      presentParticiple: "Finding (फाइंडिंग)",
      hindiMeaning: "ढूंढना (Dhoondhna)",
      example: "I found my keys. (मैंने अपनी चाबियाँ ढूंढी।)"
    },
    {
      number: 98,
      verb: "Fix (फिक्स)",
      pastSimple: "Fixed (फिक्सड)",
      pastParticiple: "Fixed (फिक्सड)",
      presentParticiple: "Fixing (फिक्सिंग)",
      hindiMeaning: "ठीक करना (Theek Karna)",
      example: "He fixed the broken chair. (उसने टूटी हुई कुर्सी ठीक की।)"
    },
    {
      number: 99,
      verb: "Fly (फ्लाई)",
      pastSimple: "Flew (फ्लू)",
      pastParticiple: "Flown (फ्लोन)",
      presentParticiple: "Flying (फ्लाइंग)",
      hindiMeaning: "उड़ना (Udna)",
      example: "Birds fly in the sky. (पक्षी आकाश में उड़ते हैं।)"
    },
    {
      number: 100,
      verb: "Forget (फॉरगेट)",
      pastSimple: "Forgot (फॉरगॉट)",
      pastParticiple: "Forgotten (फॉरगॉटन)",
      presentParticiple: "Forgetting (फॉरगेटिंग)",
      hindiMeaning: "भूलना (Bhoolna)",
      example: "I forgot your birthday. (मैंने तुम्हारा जन्मदिन भूल गया।)"
    },
    {
      number: 101,
      verb: "Get (गेट)",
      pastSimple: "Got (गॉट)",
      pastParticiple: "Gotten (गॉटन)",
      presentParticiple: "Getting (गेटिंग)",
      hindiMeaning: "पाना (Pana)",
      example: "I got a new job. (मुझे नई नौकरी मिली।)"
    },
    {
      number: 102,
      verb: "Give (गिव)",
      pastSimple: "Gave (गेव)",
      pastParticiple: "Given (गिवन)",
      presentParticiple: "Giving (गिविंग)",
      hindiMeaning: "देना (Dena)",
      example: "She gave me a gift. (उसने मुझे एक तोहफा दिया।)"
    },
    {
      number: 103,
      verb: "Go (गो)",
      pastSimple: "Went (वेंट)",
      pastParticiple: "Gone (गॉन)",
      presentParticiple: "Going (गोइंग)",
      hindiMeaning: "जाना (Jana)",
      example: "We went to the park. (हम पार्क गए।)"
    },
    {
      number: 104,
      verb: "Have (हैव)",
      pastSimple: "Had (हैड)",
      pastParticiple: "Had (हैड)",
      presentParticiple: "Having (हैविंग)",
      hindiMeaning: "होना (Hona)",
      example: "I have a car. (मेरे पास एक कार है।)"
    },
    {
      number: 105,
      verb: "Help (हेल्प)",
      pastSimple: "Helped (हेल्पड)",
      pastParticiple: "Helped (हेल्पड)",
      presentParticiple: "Helping (हेल्पिंग)",
      hindiMeaning: "मदद करना (Madad Karna)",
      example: "She helped me with the homework. (उसने मेरी होमवर्क में मदद की।)"
    },
    {
      number: 106,
      verb: "Hold (होल्ड)",
      pastSimple: "Held (हेल्ड)",
      pastParticiple: "Held (हेल्ड)",
      presentParticiple: "Holding (होल्डिंग)",
      hindiMeaning: "पकड़ना (Pakadna)",
      example: "He held my hand. (उसने मेरा हाथ पकड़ा।)"
    },
    {
      number: 107,
      verb: "Hop (हॉप)",
      pastSimple: "Hopped (हॉप्ड)",
      pastParticiple: "Hopped (हॉप्ड)",
      presentParticiple: "Hopping (हॉपिंग)",
      hindiMeaning: "कूदना (Koodna)",
      example: "The frog hopped away. (मेंढ़क कूद कर चला गया।)"
    },
    {
      number: 108,
      verb: "Hurt (हर्ट)",
      pastSimple: "Hurt (हर्ट)",
      pastParticiple: "Hurt (हर्ट)",
      presentParticiple: "Hurt (हर्ट)",
      hindiMeaning: "चोट लगाना (Chot Lagana)",
      example: "I hurt my leg. (मैंने अपनी टांग में चोट लगाई।)"
    },
    {
      number: 109,
      verb: "Keep (कीप)",
      pastSimple: "Kept (केप्ट)",
      pastParticiple: "Kept (केप्ट)",
      presentParticiple: "Keeping (कीपिंग)",
      hindiMeaning: "रखना (Rakhna)",
      example: "Keep the book on the table. (किताब को मेज पर रखो।)"
    },
    {
      number: 110,
      verb: "Know (नौ)",
      pastSimple: "Knew (न्यू)",
      pastParticiple: "Known (नोन)",
      presentParticiple: "Knowing (नौइंग)",
      hindiMeaning: "जानना (Janna)",
      example: "I know her very well. (मैं उसे बहुत अच्छे से जानता हूँ।)"
    },
    {
      number: 111,
      verb: "Learn (लर्न)",
      pastSimple: "Learned (लर्नड)",
      pastParticiple: "Learned (लर्नड)",
      presentParticiple: "Learning (लर्निंग)",
      hindiMeaning: "सिखना (Sikhna)",
      example: "She is learning English. (वह अंग्रेजी सीख रही है।)"
    },
    {
      number: 112,
      verb: "Leave (लीव)",
      pastSimple: "Left (लेफ्ट)",
      pastParticiple: "Left (लेफ्ट)",
      presentParticiple: "Leaving (लीविंग)",
      hindiMeaning: "जाना (Jana)",
      example: "I leave the house at 8 AM. (मैं घर 8 बजे सुबह छोड़ता हूँ।)"
    },
    {
      number: 113,
      verb: "Let (लेट)",
      pastSimple: "Let (लेट)",
      pastParticiple: "Let (लेट)",
      presentParticiple: "Letting (लेटिंग)",
      hindiMeaning: "इजाज़त देना (Ijazat Dena)",
      example: "Please let me go. (कृपया मुझे जाने दो।)"
    },
    {
      number: 114,
      verb: "Listen (लिसन)",
      pastSimple: "Listened (लिसनड)",
      pastParticiple: "Listened (लिसनड)",
      presentParticiple: "Listening (लिसनिंग)",
      hindiMeaning: "सुनना (Sunna)",
      example: "I listen to music every day. (मैं हर दिन संगीत सुनता हूँ।)"
    },
    {
      number: 115,
      verb: "Live (लिव)",
      pastSimple: "Lived (लिवड)",
      pastParticiple: "Lived (लिवड)",
      presentParticiple: "Living (लिविंग)",
      hindiMeaning: "जीना (Jeena)",
      example: "They live in a big house. (वे एक बड़े घर में रहते हैं।)"
    },
    {
      number: 116,
      verb: "Look (लुक)",
      pastSimple: "Looked (लुक्ड)",
      pastParticiple: "Looked (लुक्ड)",
      presentParticiple: "Looking (लुकिंग)",
      hindiMeaning: "देखना (Dekhna)",
      example: "Look at that beautiful painting. (वह सुंदर चित्र देखो।)"
    },
    {
      number: 117,
      verb: "Love (लव)",
      pastSimple: "Loved (लव्ड)",
      pastParticiple: "Loved (लव्ड)",
      presentParticiple: "Loving (लविंग)",
      hindiMeaning: "प्यार करना (Pyar Karna)",
      example: "I love reading books. (मुझे किताबें पढ़ना पसंद है।)"
    },
    {
      number: 118,
      verb: "Make (मेक)",
      pastSimple: "Made (मेड)",
      pastParticiple: "Made (मेड)",
      presentParticiple: "Making (मेकिंग)",
      hindiMeaning: "बनाना (Banana)",
      example: "She made a cake. (उसने एक केक बनाया।)"
    },
    {
      number: 119,
      verb: "Meet (मीट)",
      pastSimple: "Met (मेट)",
      pastParticiple: "Met (मेट)",
      presentParticiple: "Meeting (मीटिंग)",
      hindiMeaning: "मिलना (Milna)",
      example: "I met him yesterday. (मैं उससे कल मिला।)"
    },
    {
      number: 120,
      verb: "Move (मूव)",
      pastSimple: "Moved (मूवड)",
      pastParticiple: "Moved (मूवड)",
      presentParticiple: "Moving (मूविंग)",
      hindiMeaning: "हिलाना (Hilaana)",
      example: "He moved the chair. (उसने कुर्सी हिलाई।)"
    },
    {
      number: 121,
      verb: "Need (नीड)",
      pastSimple: "Needed (नीडड)",
      pastParticiple: "Needed (नीडड)",
      presentParticiple: "Needing (नीडिंग)",
      hindiMeaning: "जरूरत होना (Zarurat Hona)",
      example: "I need a pen. (मुझे एक कलम चाहिए।)"
    },
    {
      number: 122,
      verb: "Open (ओपन)",
      pastSimple: "Opened (ओपंड)",
      pastParticiple: "Opened (ओपंड)",
      presentParticiple: "Opening (ओपनिंग)",
      hindiMeaning: "खोलना (Kholna)",
      example: "She opened the window. (उसने खिड़की खोली।)"
    },
    {
      number: 123,
      verb: "Order (ऑर्डर)",
      pastSimple: "Ordered (ऑर्डर्ड)",
      pastParticiple: "Ordered (ऑर्डर्ड)",
      presentParticiple: "Ordering (ऑर्डरिंग)",
      hindiMeaning: "आदेश देना (Aadesh Dena)",
      example: "I ordered a pizza. (मैंने पिज़्ज़ा ऑर्डर किया।)"
    },
    {
      number: 124,
      verb: "Play (प्ले)",
      pastSimple: "Played (प्लेड)",
      pastParticiple: "Played (प्लेड)",
      presentParticiple: "Playing (प्लेइंग)",
      hindiMeaning: "खेलना (Khelna)",
      example: "Children play outside. (बच्चे बाहर खेलते हैं।)"
    },
    {
      number: 125,
      verb: "Prefer (प्रेफर)",
      pastSimple: "Preferred (प्रेफर्ड)",
      pastParticiple: "Preferred (प्रेफर्ड)",
      presentParticiple: "Preferring (प्रेफरिंग)",
      hindiMeaning: "प्राथमिकता देना (Prathmikta Dena)",
      example: "I prefer tea to coffee. (मुझे चाय कॉफी से ज्यादा पसंद है।)"
    },
    {
      number: 126,
      verb: "Read (रीड)",
      pastSimple: "Read (रेड)",
      pastParticiple: "Read (रेड)",
      presentParticiple: "Reading (रीडिंग)",
      hindiMeaning: "पढ़ना (Padhna)",
      example: "I read a book yesterday. (मैंने कल एक किताब पढ़ी।)"
    },
    {
      number: 127,
      verb: "Relax (रिलैक्स)",
      pastSimple: "Relaxed (रिलैक्स्ड)",
      pastParticiple: "Relaxed (रिलैक्स्ड)",
      presentParticiple: "Relaxing (रिलैक्सिंग)",
      hindiMeaning: "आराम करना (Aaram Karna)",
      example: "She is relaxing after work. (वह काम के बाद आराम कर रही है।)"
    },
    {
      number: 128,
      verb: "Remember (रीमेंबर)",
      pastSimple: "Remembered (रीमेंबर्ड)",
      pastParticiple: "Remembered (रीमेंबर्ड)",
      presentParticiple: "Remembering (रीमेंबिरिंग)",
      hindiMeaning: "याद रखना (Yaad Rakhna)",
      example: "I remembered to bring my phone. (मुझे अपना फोन लाना याद रहा।)"
    },
    {
      number: 129,
      verb: "Run (रन)",
      pastSimple: "Ran (रैन)",
      pastParticiple: "Run (रन)",
      presentParticiple: "Running (रनिंग)",
      hindiMeaning: "दौड़ना (Daudna)",
      example: "He runs every morning. (वह हर सुबह दौड़ता है।)"
    },
    {
      number: 130,
      verb: "Say (से)",
      pastSimple: "Said (सैड)",
      pastParticiple: "Said (सैड)",
      presentParticiple: "Saying (सेइंग)",
      hindiMeaning: "कहना (Kehna)",
      example: "She said hello to me. (उसने मुझसे हेलो कहा।)"
    },
    {
      number: 131,
      verb: "See (सी)",
      pastSimple: "Saw (सॉ)",
      pastParticiple: "Seen (सीन)",
      presentParticiple: "Seeing (सीइंग)",
      hindiMeaning: "देखना (Dekhna)",
      example: "I saw a movie last night. (मैंने कल रात एक फिल्म देखी।)"
    },
    {
      number: 132,
      verb: "Sell (सेल)",
      pastSimple: "Sold (सोब्ड)",
      pastParticiple: "Sold (सोब्ड)",
      presentParticiple: "Selling (सेलिंग)",
      hindiMeaning: "बेचना (Bechna)",
      example: "She sold her old car. (उसने अपनी पुरानी कार बेची।)"
    },
    {
      number: 133,
      verb: "Send (सेंड)",
      pastSimple: "Sent (सेंट)",
      pastParticiple: "Sent (सेंट)",
      presentParticiple: "Sending (सेंडिंग)",
      hindiMeaning: "भेजना (Bhejna)",
      example: "I sent an email. (मैंने एक ईमेल भेजा।)"
    },
    {
      number: 134,
      verb: "Sit (सिट)",
      pastSimple: "Sat (सैट)",
      pastParticiple: "Sat (सैट)",
      presentParticiple: "Sitting (सिटिंग)",
      hindiMeaning: "बैठना (Baithna)",
      example: "She sat on the chair. (वह कुर्सी पर बैठी।)"
    },
    {
      number: 135,
      verb: "Sleep (स्लीप)",
      pastSimple: "Slept (स्लेप्ट)",
      pastParticiple: "Slept (स्लेप्ट)",
      presentParticiple: "Sleeping (स्लीपिंग)",
      hindiMeaning: "सोना (Sona)",
      example: "I sleep for eight hours every night. (मैं हर रात आठ घंटे सोता हूँ।)"
    },
    {
      number: 136,
      verb: "Speak (स्पीक)",
      pastSimple: "Spoke (स्पोक)",
      pastParticiple: "Spoken (स्पोकन)",
      presentParticiple: "Speaking (स्पीकिंग)",
      hindiMeaning: "बोलना (Bolna)",
      example: "She speaks English very well. (वह बहुत अच्छे से अंग्रेजी बोलती है।)"
    },
    {
      number: 137,
      verb: "Spend (स्पेंड)",
      pastSimple: "Spent (स्पेंट)",
      pastParticiple: "Spent (स्पेंट)",
      presentParticiple: "Spending (स्पेंडिंग)",
      hindiMeaning: "खर्च करना (Kharch Karna)",
      example: "I spent my holiday at the beach. (मैंने अपनी छुट्टियाँ समुद्र तट पर बिताईं।)"
    },
    {
      number: 138,
      verb: "Stand (स्टैंड)",
      pastSimple: "Stood (स्टूड)",
      pastParticiple: "Stood (स्टूड)",
      presentParticiple: "Standing (स्टैंडिंग)",
      hindiMeaning: "खड़ा होना (Khada Hona)",
      example: "He stood at the door. (वह दरवाजे पर खड़ा था।)"
    },
    {
      number: 139,
      verb: "Start (स्टार्ट)",
      pastSimple: "Started (स्टार्टेड)",
      pastParticiple: "Started (स्टार्टेड)",
      presentParticiple: "Starting (स्टार्टिंग)",
      hindiMeaning: "शुरू करना (Shuru Karna)",
      example: "They started a new project. (उन्होंने एक नया प्रोजेक्ट शुरू किया।)"
    },
    {
      number: 140,
      verb: "Study (स्टडी)",
      pastSimple: "Studied (स्टडीड)",
      pastParticiple: "Studied (स्टडीड)",
      presentParticiple: "Studying (स्टडीइंग)",
      hindiMeaning: "अध्यान करना (Adhyayan Karna)",
      example: "I study every day. (मैं हर दिन पढ़ाई करता हूँ।)"
    },
    {
      number: 141,
      verb: "Take (टेक)",
      pastSimple: "Took (टूक)",
      pastParticiple: "Taken (टेकन)",
      presentParticiple: "Taking (टेकिंग)",
      hindiMeaning: "लेना (Lena)",
      example: "She took the book from the shelf. (उसने किताब शेल्फ से ली।)"
    },
    {
      number: 142,
      verb: "Talk (टॉक)",
      pastSimple: "Talked (टॉकड)",
      pastParticiple: "Talked (टॉकड)",
      presentParticiple: "Talking (टॉकिंग)",
      hindiMeaning: "बात करना (Baat Karna)",
      example: "We talked for hours. (हमने घंटों बात की।)"
    },
    {
      number: 143,
      verb: "Teach (टीच)",
      pastSimple: "Taught (टॉट)",
      pastParticiple: "Taught (टॉट)",
      presentParticiple: "Teaching (टीचिंग)",
      hindiMeaning: "सिखाना (Sikhana)",
      example: "She teaches English at school. (वह स्कूल में अंग्रेजी पढ़ाती है।)"
    },
    {
      number: 144,
      verb: "Think (थिंक)",
      pastSimple: "Thought (थॉट)",
      pastParticiple: "Thought (थॉट)",
      presentParticiple: "Thinking (थिंकिंग)",
      hindiMeaning: "सोचना (Sochna)",
      example: "I think it's a good idea. (मुझे लगता है कि यह अच्छा विचार है।)"
    },
    {
      number: 145,
      verb: "Throw (थ्रो)",
      pastSimple: "Threw (थ्रू)",
      pastParticiple: "Thrown (थ्रोन)",
      presentParticiple: "Throwing (थ्रोइंग)",
      hindiMeaning: "फेंकना (Fekna)",
      example: "She threw the ball to the dog. (उसने गेंद कुत्ते को फेंकी।)"
    },
    {
      number: 146,
      verb: "Understand (अंडरस्टैंड)",
      pastSimple: "Understood (अंडरस्टूड)",
      pastParticiple: "Understood (अंडरस्टूड)",
      presentParticiple: "Understanding (अंडरस्टैंडिंग)",
      hindiMeaning: "समझना (Samajhna)",
      example: "I understood the problem. (मैंने समस्या समझी।)"
    },
    {
      number: 147,
      verb: "Use (यूज़)",
      pastSimple: "Used (यूज़्ड)",
      pastParticiple: "Used (यूज़्ड)",
      presentParticiple: "Using (यूज़िंग)",
      hindiMeaning: "उपयोग करना (Upyog Karna)",
      example: "I use my phone to check emails. (मैं ईमेल चेक करने के लिए अपना फोन उपयोग करता हूँ।)"
    },
    {
      number: 148,
      verb: "Visit (विजिट)",
      pastSimple: "Visited (विजिटेड)",
      pastParticiple: "Visited (विजिटेड)",
      presentParticiple: "Visiting (विजिटिंग)",
      hindiMeaning: "यात्रा करना (Yatra Karna)",
      example: "I visited my grandparents last weekend. (मैंने पिछले सप्ताहांत अपने दादी-दादी से मुलाकात की।)"
    },
    {
      number: 149,
      verb: "Wait (वेट)",
      pastSimple: "Waited (वेटेड)",
      pastParticiple: "Waited (वेटेड)",
      presentParticiple: "Waiting (वेटिंग)",
      hindiMeaning: "इंतजार करना (Intezaar Karna)",
      example: "We waited for the bus. (हम बस का इंतजार कर रहे थे।)"
    },
    {
      number: 150,
      verb: "Walk (वॉक)",
      pastSimple: "Walked (वॉकड)",
      pastParticiple: "Walked (वॉकड)",
      presentParticiple: "Walking (वॉकिंग)",
      hindiMeaning: "चलना (Chalna)",
      example: "I walk to school every day. (मैं हर दिन स्कूल जाता हूँ।)"
    },
    {
      number: 151,
      verb: "Want (वांट)",
      pastSimple: "Wanted (वांटेड)",
      pastParticiple: "Wanted (वांटेड)",
      presentParticiple: "Wanting (वांटिंग)",
      hindiMeaning: "चाहना (Chahna)",
      example: "I want a cup of coffee. (मुझे एक कप कॉफी चाहिए।)"
    },
    {
      number: 152,
      verb: "Work (वर्क)",
      pastSimple: "Worked (वर्कड)",
      pastParticiple: "Worked (वर्कड)",
      presentParticiple: "Working (वर्किंग)",
      hindiMeaning: "काम करना (Kaam Karna)",
      example: "He works in an office. (वह एक कार्यालय में काम करता है।)"
    },
    {
      number: 153,
      verb: "Write (राइट)",
      pastSimple: "Wrote (रोट)",
      pastParticiple: "Written (रिटन)",
      presentParticiple: "Writing (राइटिंग)",
      hindiMeaning: "लिखना (Likhna)",
      example: "She writes letters every week. (वह हर हफ्ते पत्र लिखती है।)"
    },
    {
      number: 154,
      verb: "Win (विन)",
      pastSimple: "Won (वॉन)",
      pastParticiple: "Won (वॉन)",
      presentParticiple: "Winning (विनिंग)",
      hindiMeaning: "जीतना (Jeetna)",
      example: "They won the match. (उन्होंने मैच जीत लिया।)"
    },
    {
      number: 155,
      verb: "Watch (वॉच)",
      pastSimple: "Watched (वॉच्ड)",
      pastParticiple: "Watched (वॉच्ड)",
      presentParticiple: "Watching (वॉचिंग)",
      hindiMeaning: "देखना (Dekhna)",
      example: "I watch movies every weekend. (मैं हर सप्ताहांत फिल्में देखता हूँ।)"
    },
    {
      number: 156,
      verb: "Wish (विश)",
      pastSimple: "Wished (विश्ड)",
      pastParticiple: "Wished (विश्ड)",
      presentParticiple: "Wishing (विशिंग)",
      hindiMeaning: "इच्छा करना (Ichha Karna)",
      example: "I wish you all the best. (मैं आपको शुभकामनाएं देता हूँ।)"
    },
    {
      number: 157,
      verb: "Yell (येल)",
      pastSimple: "Yelled (येल्ड)",
      pastParticiple: "Yelled (येल्ड)",
      presentParticiple: "Yelling (येलिंग)",
      hindiMeaning: "चिल्लाना (Chillana)",
      example: "He yelled at the kids. (उसने बच्चों पर चिल्लाया।)"
    },
    {
      number: 158,
      verb: "Zoom (जूम)",
      pastSimple: "Zoomed (जूमड)",
      pastParticiple: "Zoomed (जूमड)",
      presentParticiple: "Zooming (जूमिंग)",
      hindiMeaning: "तेज़ी से चलना (Tezi Se Chalna)",
      example: "The car zoomed past us. (गाड़ी हमारे पास से तेज़ी से निकली।)"
    },
    {
      number: 159,
      verb: "Accept (एक्सेप्ट)",
      pastSimple: "Accepted (एक्सेप्टेड)",
      pastParticiple: "Accepted (एक्सेप्टेड)",
      presentParticiple: "Accepting (एक्सेप्टिंग)",
      hindiMeaning: "स्वीकार करना (Sweekar Karna)",
      example: "She accepted the invitation. (उसने निमंत्रण स्वीकार किया।)"
    },
    {
      number: 160,
      verb: "Achieve (अचीव)",
      pastSimple: "Achieved (अचीव्ड)",
      pastParticiple: "Achieved (अचीव्ड)",
      presentParticiple: "Achieving (अचीविंग)",
      hindiMeaning: "प्राप्त करना (Prapt Karna)",
      example: "He achieved his goals. (उसने अपने लक्ष्य प्राप्त किए।)"
    },
    {
      number: 161,
      verb: "Admire (एडमायर)",
      pastSimple: "Admired (एडमायर्ड)",
      pastParticiple: "Admired (एडमायर्ड)",
      presentParticiple: "Admiring (एडमायरिंग)",
      hindiMeaning: "प्रशंसा करना (Prashansa Karna)",
      example: "I admire her dedication. (मैं उसकी समर्पण की प्रशंसा करता हूँ।)"
    },
    {
      number: 162,
      verb: "Advise (एडवाइज)",
      pastSimple: "Advised (एडवाइज्ड)",
      pastParticiple: "Advised (एडवाइज्ड)",
      presentParticiple: "Advising (एडवाइजिंग)",
      hindiMeaning: "सलाह देना (Salah Dena)",
      example: "I advise you to stay calm. (मैं आपको शांत रहने की सलाह देता हूँ।)"
    },
    {
      number: 163,
      verb: "Allow (अलाउ)",
      pastSimple: "Allowed (अलाउड)",
      pastParticiple: "Allowed (अलाउड)",
      presentParticiple: "Allowing (अलाउइंग)",
      hindiMeaning: "इजाजत देना (Ijazat Dena)",
      example: "They allowed us to enter. (उन्होंने हमें प्रवेश करने की इजाजत दी।)"
    },
    {
      number: 164,
      verb: "Answer (आंसर)",
      pastSimple: "Answered (आंसरड)",
      pastParticiple: "Answered (आंसरड)",
      presentParticiple: "Answering (आंसरिंग)",
      hindiMeaning: "उत्तर देना (Uttar Dena)",
      example: "He answered the phone. (उसने फोन का उत्तर दिया।)"
    },
    {
      number: 165,
      verb: "Arrange (अरेन्ज)",
      pastSimple: "Arranged (अरेन्ज्ड)",
      pastParticiple: "Arranged (अरेन्ज्ड)",
      presentParticiple: "Arranging (अरेन्जिंग)",
      hindiMeaning: "व्यवस्था करना (Vyavastha Karna)",
      example: "She arranged the chairs in a circle. (उसने कुर्सियाँ एक घेरे में व्यवस्थित की।)"
    },
    {
      number: 166,
      verb: "Attack (अटैक)",
      pastSimple: "Attacked (अटैक्ड)",
      pastParticiple: "Attacked (अटैक्ड)",
      presentParticiple: "Attacking (अटैकिंग)",
      hindiMeaning: "हमला करना (Hamla Karna)",
      example: "The dog attacked the intruder. (कुत्ते ने घुसपैठिए पर हमला किया।)"
    },
    {
      number: 167,
      verb: "Avoid (अवॉइड)",
      pastSimple: "Avoided (अवॉइडेड)",
      pastParticiple: "Avoided (अवॉइडेड)",
      presentParticiple: "Avoiding (अवॉइडिंग)",
      hindiMeaning: "बचाना (Bachana)",
      example: "I try to avoid junk food. (मैं जंक फूड से बचने की कोशिश करता हूँ।)"
    },
    {
      number: 168,
      verb: "Bake (बेक)",
      pastSimple: "Baked (बैक्ड)",
      pastParticiple: "Baked (बैक्ड)",
      presentParticiple: "Baking (बैकिंग)",
      hindiMeaning: "पकाना (Pakana)",
      example: "She baked a cake for the party. (उसने पार्टी के लिए एक केक बेक किया।)"
    },
    {
      number: 169,
      verb: "Be (बी)",
      pastSimple: "Was/Were (वॉज़/वेर)",
      pastParticiple: "Been (बीन)",
      presentParticiple: "Being (बीइंग)",
      hindiMeaning: "होना (Hona)",
      example: "I am a teacher. (मैं एक शिक्षक हूँ।)"
    },
    {
      number: 170,
      verb: "Beat (बीट)",
      pastSimple: "Beat (बीट)",
      pastParticiple: "Beaten (बीटन)",
      presentParticiple: "Beating (बीटिंग)",
      hindiMeaning: "पीटना (Peetna)",
      example: "He beat the drums loudly. (उसने ढोल को जोर से पीटा।)"
    },
    {
      number: 171,
      verb: "Become (बिकम)",
      pastSimple: "Became (बिकेम)",
      pastParticiple: "Become (बिकम)",
      presentParticiple: "Becoming (बिकमिंग)",
      hindiMeaning: "बनना (Banna)",
      example: "She became a doctor. (वह डॉक्टर बन गई।)"
    },
    {
      number: 172,
      verb: "Begin (बिगिन)",
      pastSimple: "Began (बिगैन)",
      pastParticiple: "Begun (बिगन)",
      presentParticiple: "Beginning (बिगिनिंग)",
      hindiMeaning: "शुरू करना (Shuru Karna)",
      example: "He began his career in 2000. (उसने 2000 में अपनी करियर की शुरुआत की।)"
    },
    {
      number: 173,
      verb: "Believe (बिलीव)",
      pastSimple: "Believed (बिलीव्ड)",
      pastParticiple: "Believed (बिलीव्ड)",
      presentParticiple: "Believing (बिलीविंग)",
      hindiMeaning: "विश्वास करना (Vishwas Karna)",
      example: "I believe in hard work. (मुझे मेहनत में विश्वास है।)"
    },
    {
      number: 174,
      verb: "Borrow (बॉरो)",
      pastSimple: "Borrowed (बॉरोड)",
      pastParticiple: "Borrowed (बॉरोड)",
      presentParticiple: "Borrowing (बॉरोइंग)",
      hindiMeaning: "उधार लेना (Udhar Lena)",
      example: "Can I borrow your pen? (क्या मैं आपकी कलम उधार ले सकता हूँ?)"
    },
    {
      number: 175,
      verb: "Break (ब्रेक)",
      pastSimple: "Broke (ब्रोक)",
      pastParticiple: "Broken (ब्रोकन)",
      presentParticiple: "Breaking (ब्रेकिंग)",
      hindiMeaning: "टूटना (Tootna)",
      example: "I accidentally broke the glass. (मैंने गलती से गिलास तोड़ दिया।)"
    },
    {
      number: 176,
      verb: "Bring (ब्रिंग)",
      pastSimple: "Brought (ब्रॉट)",
      pastParticiple: "Brought (ब्रॉट)",
      presentParticiple: "Bringing (ब्रिंगिंग)",
      hindiMeaning: "लाना (Lana)",
      example: "She brought a gift for him. (उसने उसके लिए एक उपहार लाया।)"
    },
    {
      number: 177,
      verb: "Build (बिल्ड)",
      pastSimple: "Built (बिल्ट)",
      pastParticiple: "Built (बिल्ट)",
      presentParticiple: "Building (बिल्डिंग)",
      hindiMeaning: "बनाना (Banana)",
      example: "They built a new house. (उन्होंने एक नया घर बनाया।)"
    },
    {
      number: 178,
      verb: "Buy (बाय)",
      pastSimple: "Bought (बॉट)",
      pastParticiple: "Bought (बॉट)",
      presentParticiple: "Buying (बाइंग)",
      hindiMeaning: "खरीदना (Kharidna)",
      example: "I bought a new phone yesterday. (मैंने कल नया फोन खरीदा।)"
    },
    {
      number: 179,
      verb: "Call (कॉल)",
      pastSimple: "Called (कॉल्ड)",
      pastParticiple: "Called (कॉल्ड)",
      presentParticiple: "Calling (कॉलिंग)",
      hindiMeaning: "बुलाना (Bulana)",
      example: "She called me last night. (उसने मुझे कल रात बुलाया।)"
    },
    {
      number: 180,
      verb: "Catch (कैच)",
      pastSimple: "Caught (कॉर्ट)",
      pastParticiple: "Caught (कॉर्ट)",
      presentParticiple: "Catching (कैचिंग)",
      hindiMeaning: "पकड़ना (Pakadna)",
      example: "I caught the ball. (मैंने गेंद पकड़ी।)"
    },
    {
      number: 181,
      verb: "Change (चेंज)",
      pastSimple: "Changed (चेंज्ड)",
      pastParticiple: "Changed (चेंज्ड)",
      presentParticiple: "Changing (चेंजिंग)",
      hindiMeaning: "बदलना (Badalna)",
      example: "She changed her clothes. (उसने अपने कपड़े बदले।)"
    },
    {
      number: 182,
      verb: "Clean (क्लीन)",
      pastSimple: "Cleaned (क्लीन्ड)",
      pastParticiple: "Cleaned (क्लीन्ड)",
      presentParticiple: "Cleaning (क्लीनिंग)",
      hindiMeaning: "साफ़ करना (Saaf Karna)",
      example: "I cleaned my room yesterday. (मैंने कल अपना कमरा साफ किया।)"
    },
    {
      number: 183,
      verb: "Close (क्लोज़)",
      pastSimple: "Closed (क्लोज्ड)",
      pastParticiple: "Closed (क्लोज्ड)",
      presentParticiple: "Closing (क्लोज़िंग)",
      hindiMeaning: "बंद करना (Band Karna)",
      example: "Please close the door. (कृपया दरवाजा बंद करें।)"
    },
    {
      number: 184,
      verb: "Combine (कंबाइन)",
      pastSimple: "Combined (कंबाइंड)",
      pastParticiple: "Combined (कंबाइंड)",
      presentParticiple: "Combining (कंबाइंग)",
      hindiMeaning: "मिलाना (Milana)",
      example: "They combined their efforts to succeed. (उन्होंने सफलता पाने के लिए अपने प्रयासों को मिलाया।)"
    },
    {
      number: 185,
      verb: "Cook (कुक)",
      pastSimple: "Cooked (कुक्ड)",
      pastParticiple: "Cooked (कुक्ड)",
      presentParticiple: "Cooking (कुकिंग)",
      hindiMeaning: "पकाना (Pakana)",
      example: "She cooked a delicious meal. (उसने स्वादिष्ट खाना पकाया।)"
    },
    {
      number: 186,
      verb: "Create (क्रिएट)",
      pastSimple: "Created (क्रिएटेड)",
      pastParticiple: "Created (क्रिएटेड)",
      presentParticiple: "Creating (क्रिएटिंग)",
      hindiMeaning: "सृजन करना (Srijan Karna)",
      example: "He created a masterpiece. (उसने एक उत्कृष्ट कृति बनाई।)"
    },
    {
      number: 187,
      verb: "Dance (डांस)",
      pastSimple: "Danced (डांस्ड)",
      pastParticiple: "Danced (डांस्ड)",
      presentParticiple: "Dancing (डांसिंग)",
      hindiMeaning: "नृत्य करना (Nritya Karna)",
      example: "They danced at the party. (वे पार्टी में नृत्य कर रहे थे।)"
    },
    {
      number: 188,
      verb: "Decide (डिसाइड)",
      pastSimple: "Decided (डिसाइडेड)",
      pastParticiple: "Decided (डिसाइडेड)",
      presentParticiple: "Deciding (डिसाइडिंग)",
      hindiMeaning: "निर्णय लेना (Nirnay Lena)",
      example: "She decided to go to the cinema. (उसने सिनेमा जाने का निर्णय लिया।)"
    },
    {
      number: 189,
      verb: "Deliver (डिलीवर)",
      pastSimple: "Delivered (डिलीवरड)",
      pastParticiple: "Delivered (डिलीवरड)",
      presentParticiple: "Delivering (डिलीवरिंग)",
      hindiMeaning: "वितरित करना (Vitrit Karna)",
      example: "The mailman delivered the package. (मेलमैन ने पैकेज वितरित किया।)"
    },
    {
      number: 190,
      verb: "Demand (डिमांड)",
      pastSimple: "Demanded (डिमांडेड)",
      pastParticiple: "Demanded (डिमांडेड)",
      presentParticiple: "Demanding (डिमांडिंग)",
      hindiMeaning: "मांग करना (Maang Karna)",
      example: "They demanded an explanation. (उन्होंने स्पष्टीकरण की मांग की।)"
    },
    {
      number: 191,
      verb: "Depart (डिपार्ट)",
      pastSimple: "Departed (डिपार्टेड)",
      pastParticiple: "Departed (डिपार्टेड)",
      presentParticiple: "Departing (डिपार्टिंग)",
      hindiMeaning: "प्रस्थान करना (Prasthan Karna)",
      example: "The train departed on time. (ट्रेन समय पर प्रस्थान कर गई।)"
    },
    {
      number: 192,
      verb: "Describe (डिस्क्राइब)",
      pastSimple: "Described (डिस्क्राइब्ड)",
      pastParticiple: "Described (डिस्क्राइब्ड)",
      presentParticiple: "Describing (डिस्क्राइबिंग)",
      hindiMeaning: "वर्णन करना (Varnan Karna)",
      example: "She described the scene vividly. (उसने दृश्य का स्पष्ट रूप से वर्णन किया।)"
    },
    {
      number: 193,
      verb: "Destroy (डेस्ट्रॉय)",
      pastSimple: "Destroyed (डेस्ट्रॉयड)",
      pastParticiple: "Destroyed (डेस्ट्रॉयड)",
      presentParticiple: "Destroying (डेस्ट्रॉयइंग)",
      hindiMeaning: "नष्ट करना (Nasht Karna)",
      example: "The earthquake destroyed many buildings. (भूकंप ने कई इमारतों को नष्ट कर दिया।)"
    },
    {
      number: 194,
      verb: "Develop (डेवलप)",
      pastSimple: "Developed (डेवलप्ड)",
      pastParticiple: "Developed (डेवलप्ड)",
      presentParticiple: "Developing (डेवलपिंग)",
      hindiMeaning: "विकसित करना (Viksit Karna)",
      example: "The company developed new software. (कंपनी ने नया सॉफ़्टवेयर विकसित किया।)"
    },
    {
      number: 195,
      verb: "Die (डाई)",
      pastSimple: "Died (डाईड)",
      pastParticiple: "Died (डाईड)",
      presentParticiple: "Dying (डाईइंग)",
      hindiMeaning: "मरना (Marna)",
      example: "The plant died due to lack of water. (पौधा पानी की कमी के कारण मरा।)"
    },
    {
      number: 196,
      verb: "Dig (डिग)",
      pastSimple: "Dug (डग)",
      pastParticiple: "Dug (डग)",
      presentParticiple: "Digging (डिगिंग)",
      hindiMeaning: "खोदना (Khodna)",
      example: "They dug a hole in the ground. (उन्होंने जमीन में एक गड्ढा खोदा।)"
    },
    {
      number: 197,
      verb: "Do (डू)",
      pastSimple: "Did (डिड)",
      pastParticiple: "Done (डन)",
      presentParticiple: "Doing (डूइंग)",
      hindiMeaning: "करना (Karna)",
      example: "I did my homework. (मैंने अपना होमवर्क किया।)"
    },
    {
      number: 198,
      verb: "Draw (ड्रॉ)",
      pastSimple: "Drew (ड्रू)",
      pastParticiple: "Drawn (ड्रॉन)",
      presentParticiple: "Drawing (ड्रॉइंग)",
      hindiMeaning: "चित्रित करना (Chitrit Karna)",
      example: "She drew a beautiful picture. (उसने एक सुंदर चित्र बनाया।)"
    },
    {
      number: 199,
      verb: "Drink (ड्रिंक)",
      pastSimple: "Drank (ड्रैंक्स)",
      pastParticiple: "Drunk (ड्रंक्स)",
      presentParticiple: "Drinking (ड्रिंकिंग)",
      hindiMeaning: "पीना (Peena)",
      example: "He drank a glass of water. (उसने पानी का गिलास पिया।)"
    },
    {
      number: 200,
      verb: "Drive (ड्राइव)",
      pastSimple: "Drove (ड्रूव)",
      pastParticiple: "Driven (ड्रिवन)",
      presentParticiple: "Driving (ड्राइविंग)",
      hindiMeaning: "चलाना (Chalana)",
      example: "She drove to the office today. (उसने आज दफ्तर के लिए कार चलाई।)"
    },
    {
      number: 201,
      verb: "Eat (ईट)",
      pastSimple: "Ate (एट)",
      pastParticiple: "Eaten (ईटन)",
      presentParticiple: "Eating (ईटिंग)",
      hindiMeaning: "खाना (Khana)",
      example: "We ate lunch together. (हमने साथ में लंच खाया।)"
    },
    {
      number: 202,
      verb: "Enjoy (एन्जॉय)",
      pastSimple: "Enjoyed (एन्जॉयड)",
      pastParticiple: "Enjoyed (एन्जॉयड)",
      presentParticiple: "Enjoying (एन्जॉयइंग)",
      hindiMeaning: "आनंद लेना (Anand Lena)",
      example: "She enjoys listening to music. (वह संगीत सुनने का आनंद लेती है।)"
    },
    {
      number: 203,
      verb: "Explain (एक्सप्लेन)",
      pastSimple: "Explained (एक्सप्लेंड)",
      pastParticiple: "Explained (एक्सप्लेंड)",
      presentParticiple: "Explaining (एक्सप्लेनिंग)",
      hindiMeaning: "व्याख्या करना (Vyakhya Karna)",
      example: "He explained the rules clearly. (उसने नियमों की स्पष्ट व्याख्या की।)"
    },
    {
      number: 204,
      verb: "Fall (फॉल)",
      pastSimple: "Fell (फेल)",
      pastParticiple: "Fallen (फॉलन)",
      presentParticiple: "Falling (फॉलिंग)",
      hindiMeaning: "गिरना (Girna)",
      example: "She fell down the stairs. (वह सीढ़ियों से गिर गई।)"
    },
    {
      number: 205,
      verb: "Feel (फील)",
      pastSimple: "Felt (फेल्ट)",
      pastParticiple: "Felt (फेल्ट)",
      presentParticiple: "Feeling (फीलिंग)",
      hindiMeaning: "महसूस करना (Mahsoos Karna)",
      example: "I felt happy after the good news. (अच्छी खबर के बाद मुझे खुशी महसूस हुई।)"
    },
    {
      number: 206,
      verb: "Fight (फाइट)",
      pastSimple: "Fought (फॉट)",
      pastParticiple: "Fought (फॉट)",
      presentParticiple: "Fighting (फाइटिंग)",
      hindiMeaning: "लड़ना (Ladna)",
      example: "They fought over the last piece of cake. (उन्होंने आखिरी टुकड़े के लिए लड़ाई की।)"
    },
    {
      number: 207,
      verb: "Find (फाइंड)",
      pastSimple: "Found (फाउंड)",
      pastParticiple: "Found (फाउंड)",
      presentParticiple: "Finding (फाइंडिंग)",
      hindiMeaning: "ढूंढना (Dhoondna)",
      example: "I found my keys. (मैंने अपनी चाबियाँ ढूंढ ली।)"
    },
    {
      number: 208,
      verb: "Fly (फ्लाइ)",
      pastSimple: "Flew (फ्लू)",
      pastParticiple: "Flown (फ्लोन)",
      presentParticiple: "Flying (फ्लाइंग)",
      hindiMeaning: "उड़ना (Udna)",
      example: "The birds are flying in the sky. (पक्षी आकाश में उड़ रहे हैं।)"
    },
    {
      number: 209,
      verb: "Forget (फॉरगेट)",
      pastSimple: "Forgot (फॉरगॉट)",
      pastParticiple: "Forgotten (फॉरगॉटन)",
      presentParticiple: "Forgetting (फॉरगेटिंग)",
      hindiMeaning: "भूलना (Bhulna)",
      example: "I forgot my wallet at home. (मैं अपना बटुआ घर पर भूल गया।)"
    },
    {
      number: 210,
      verb: "Get (गेट)",
      pastSimple: "Got (गॉट)",
      pastParticiple: "Gotten (गॉटन)",
      presentParticiple: "Getting (गेटिंग)",
      hindiMeaning: "प्राप्त करना (Prapt Karna)",
      example: "I got a new job. (मुझे नई नौकरी मिली।)"
    },
    {
      number: 211,
      verb: "Give (गिव)",
      pastSimple: "Gave (गेव)",
      pastParticiple: "Given (गिवन)",
      presentParticiple: "Giving (गिविंग)",
      hindiMeaning: "देना (Dena)",
      example: "She gave me a gift. (उसने मुझे एक उपहार दिया।)"
    },
    {
      number: 212,
      verb: "Go (गो)",
      pastSimple: "Went (वेंट)",
      pastParticiple: "Gone (गॉन)",
      presentParticiple: "Going (गोइंग)",
      hindiMeaning: "जाना (Jana)",
      example: "We went to the park yesterday. (हम कल पार्क गए थे।)"
    },
    {
      number: 213,
      verb: "Grow (ग्रो)",
      pastSimple: "Grew (ग्रू)",
      pastParticiple: "Grown (ग्रोन)",
      presentParticiple: "Growing (ग्रोइंग)",
      hindiMeaning: "बढ़ना (Badhna)",
      example: "The plants grew quickly in the spring. (वसंत में पौधे जल्दी बढ़े।)"
    },
    {
      number: 214,
      verb: "Guess (गेस)",
      pastSimple: "Guessed (गेस्ड)",
      pastParticiple: "Guessed (गेस्ड)",
      presentParticiple: "Guessing (गेसिंग)",
      hindiMeaning: "अंदाजा लगाना (Andaza Lagana)",
      example: "He guessed the correct answer. (उसने सही जवाब का अंदाजा लगाया।)"
    },
    {
      number: 215,
      verb: "Have (हैव)",
      pastSimple: "Had (हैड)",
      pastParticiple: "Had (हैड)",
      presentParticiple: "Having (हैविंग)",
      hindiMeaning: "है (Hona)",
      example: "I have a lot of work to do. (मेरे पास बहुत सा काम है।)"
    },
    {
      number: 216,
      verb: "Hear (हियर)",
      pastSimple: "Heard (हर्ड)",
      pastParticiple: "Heard (हर्ड)",
      presentParticiple: "Hearing (हियरिंग)",
      hindiMeaning: "सुनना (Sunna)",
      example: "I heard a strange noise last night. (मैंने कल रात अजीब आवाज सुनी।)"
    },
    {
      number: 217,
      verb: "Help (हेल्प)",
      pastSimple: "Helped (हेल्प्ड)",
      pastParticiple: "Helped (हेल्प्ड)",
      presentParticiple: "Helping (हेल्पिंग)",
      hindiMeaning: "मदद करना (Madad Karna)",
      example: "She helped me with my homework. (उसने मेरी होमवर्क में मदद की।)"
    },
    {
      number: 218,
      verb: "Hold (होल्ड)",
      pastSimple: "Held (हेल्ड)",
      pastParticiple: "Held (हेल्ड)",
      presentParticiple: "Holding (होल्डिंग)",
      hindiMeaning: "पकड़ना (Pakadna)",
      example: "He held the baby in his arms. (उसने बच्चे को अपनी बाहों में पकड़ा।)"
    },
    {
      number: 219,
      verb: "Hope (होप)",
      pastSimple: "Hoped (होप्ड)",
      pastParticiple: "Hoped (होप्ड)",
      presentParticiple: "Hoping (होपिंग)",
      hindiMeaning: "आशा करना (Asha Karna)",
      example: "We hope for good weather tomorrow. (हम कल अच्छे मौसम की आशा करते हैं।)"
    },
    {
      number: 220,
      verb: "Hug (हग)",
      pastSimple: "Hugged (हग्ड)",
      pastParticiple: "Hugged (हग्ड)",
      presentParticiple: "Hugging (हगिंग)",
      hindiMeaning: "गले लगाना (Gale Lagana)",
      example: "She hugged her friend tightly. (उसने अपनी दोस्त को कसकर गले लगाया।)"
    },
    {
      number: 221,
      verb: "Imagine (इमैजिन)",
      pastSimple: "Imagined (इमैजिन्ड)",
      pastParticiple: "Imagined (इमैजिन्ड)",
      presentParticiple: "Imagining (इमैजिनिंग)",
      hindiMeaning: "कल्पना करना (Kalpana Karna)",
      example: "I imagined a world without war. (मैंने एक ऐसे दुनिया की कल्पना की बिना युद्ध के।)"
    },
    {
      number: 222,
      verb: "Invite (इंवाइट)",
      pastSimple: "Invited (इंवाइटेड)",
      pastParticiple: "Invited (इंवाइटेड)",
      presentParticiple: "Inviting (इंवाइटिंग)",
      hindiMeaning: "निमंत्रण देना (Nimantran Dena)",
      example: "They invited us to their wedding. (उन्होंने हमें अपनी शादी पर निमंत्रित किया।)"
    },
    {
      number: 223,
      verb: "Join (जॉइन)",
      pastSimple: "Joined (जॉइनड)",
      pastParticiple: "Joined (जॉइनड)",
      presentParticiple: "Joining (जॉइनिंग)",
      hindiMeaning: "जोड़ना (Jodna)",
      example: "She joined the dance class yesterday. (वह कल नृत्य कक्षा में शामिल हुई।)"
    },
    {
      number: 224,
      verb: "Jump (जंप)",
      pastSimple: "Jumped (जंप्ड)",
      pastParticiple: "Jumped (जंप्ड)",
      presentParticiple: "Jumping (जंपिंग)",
      hindiMeaning: "कूदना (Koodna)",
      example: "The children jumped over the puddle. (बच्चों ने पानी की धारा के ऊपर कूदा।)"
    },
    {
      number: 225,
      verb: "Keep (कीप)",
      pastSimple: "Kept (केप्ट)",
      pastParticiple: "Kept (केप्ट)",
      presentParticiple: "Keeping (कीपिंग)",
      hindiMeaning: "रखना (Rakhna)",
      example: "She kept the book on the shelf. (उसने किताब को शेल्फ पर रखा।)"
    },
    {
      number: 226,
      verb: "Know (नौ)",
      pastSimple: "Knew (न्यू)",
      pastParticiple: "Known (नोअन)",
      presentParticiple: "Knowing (नॉइंग)",
      hindiMeaning: "जानना (Janna)",
      example: "I knew him for years. (मैं उसे सालों से जानता था।)"
    },
    {
      number: 227,
      verb: "Learn (लर्न)",
      pastSimple: "Learned (लर्न्ड)",
      pastParticiple: "Learned (लर्न्ड)",
      presentParticiple: "Learning (लर्निंग)",
      hindiMeaning: "सीखना (Seekhna)",
      example: "She is learning to play the piano. (वह पियानो बजाना सीख रही है।)"
    },
    {
      number: 228,
      verb: "Leave (लीव)",
      pastSimple: "Left (लेफ्ट)",
      pastParticiple: "Left (लेफ्ट)",
      presentParticiple: "Leaving (लीविंग)",
      hindiMeaning: "जाना (Jana)",
      example: "He left the office early today. (वह आज जल्दी दफ्तर से चला गया।)"
    },
    {
      number: 229,
      verb: "Lend (लेंड)",
      pastSimple: "Lent (लेंट)",
      pastParticiple: "Lent (लेंट)",
      presentParticiple: "Lending (लेंडिंग)",
      hindiMeaning: "उधार देना (Udhaar Dena)",
      example: "She lent me some money. (उसने मुझे कुछ पैसे उधार दिए।)"
    },
    {
      number: 230,
      verb: "Let (लेट)",
      pastSimple: "Let (लेट)",
      pastParticiple: "Let (लेट)",
      presentParticiple: "Letting (लेटिंग)",
      hindiMeaning: "इजाजत देना (Ijaazat Dena)",
      example: "Please let me know if you need help. (कृपया मुझे बताएं अगर आपको मदद की जरूरत हो।)"
    },
    {
      number: 231,
      verb: "Lie (लाइ)",
      pastSimple: "Lay (ले)",
      pastParticiple: "Lain (लेन)",
      presentParticiple: "Lying (लाइंग)",
      hindiMeaning: "लेटना (Letna)",
      example: "He lies on the bed all day. (वह पूरे दिन बिस्तर पर लेटा रहता है।)"
    },
    {
      number: 232,
      verb: "Listen (लिसन)",
      pastSimple: "Listened (लिस्टेन्ड)",
      pastParticiple: "Listened (लिस्टेन्ड)",
      presentParticiple: "Listening (लिसनिंग)",
      hindiMeaning: "सुनना (Sunna)",
      example: "She listens to music every day. (वह हर दिन संगीत सुनती है।)"
    },
    {
      number: 233,
      verb: "Live (लिव)",
      pastSimple: "Lived (लिव्ड)",
      pastParticiple: "Lived (लिव्ड)",
      presentParticiple: "Living (लिविंग)",
      hindiMeaning: "जीना (Jeena)",
      example: "They live in a big house. (वे एक बड़े घर में रहते हैं।)"
    },
    {
        number: 234,
        verb: "Look (लुक)",
        pastSimple: "Looked (लुक्ड)",
        pastParticiple: "Looked (लुक्ड)",
        presentParticiple: "Looking (लुकिंग)",
        hindiMeaning: "देखना (Dekhna)",
        example: "She looked out the window. (उसने खिड़की से बाहर देखा।)"
      },
      {
        number: 235,
        verb: "Lose (लूज़)",
        pastSimple: "Lost (लॉस्ट)",
        pastParticiple: "Lost (लॉस्ट)",
        presentParticiple: "Losing (लूजिंग)",
        hindiMeaning: "खोना (Khona)",
        example: "I lost my keys yesterday. (मैंने कल अपनी चाबियाँ खो दीं।)"
      },
      {
        number: 236,
        verb: "Love (लव)",
        pastSimple: "Loved (लव्ड)",
        pastParticiple: "Loved (लव्ड)",
        presentParticiple: "Loving (लविंग)",
        hindiMeaning: "प्यार करना (Pyaar Karna)",
        example: "She loves reading books. (वह किताबें पढ़ना पसंद करती है।)"
      },
      {
        number: 237,
        verb: "Make (मेक)",
        pastSimple: "Made (मेड)",
        pastParticiple: "Made (मेड)",
        presentParticiple: "Making (मेकिंग)",
        hindiMeaning: "बनाना (Banana)",
        example: "He made a delicious cake. (उसने एक स्वादिष्ट केक बनाया।)"
      },
      {
        number: 238,
        verb: "Meet (मीट)",
        pastSimple: "Met (मेट)",
        pastParticiple: "Met (मेट)",
        presentParticiple: "Meeting (मीटिंग)",
        hindiMeaning: "मिलना (Milna)",
        example: "We met at the park yesterday. (हम कल पार्क में मिले।)"
      },
      {
        number: 239,
        verb: "Open (ओपन)",
        pastSimple: "Opened (ओपन्ड)",
        pastParticiple: "Opened (ओपन्ड)",
        presentParticiple: "Opening (ओपनिंग)",
        hindiMeaning: "खोलना (Kholna)",
        example: "She opened the door slowly. (उसने धीरे से दरवाजा खोला।)"
      },
      {
        number: 240,
        verb: "Pay (पे)",
        pastSimple: "Paid (पेड)",
        pastParticiple: "Paid (पेड)",
        presentParticiple: "Paying (पेयिंग)",
        hindiMeaning: "भुगतान करना (Bhugtaan Karna)",
        example: "He paid the bill at the restaurant. (उसने रेस्तरां में बिल का भुगतान किया।)"
      },
      {
        number: 241,
        verb: "Play (प्ले)",
        pastSimple: "Played (प्लेड)",
        pastParticiple: "Played (प्लेड)",
        presentParticiple: "Playing (प्लेइंग)",
        hindiMeaning: "खेलना (Khelna)",
        example: "They played football in the evening. (उन्होंने शाम को फुटबॉल खेला।)"
      },
      {
        number: 242,
        verb: "Promise (प्रॉमिस)",
        pastSimple: "Promised (प्रॉमिस्ड)",
        pastParticiple: "Promised (प्रॉमिस्ड)",
        presentParticiple: "Promising (प्रॉमिसिंग)",
        hindiMeaning: "वादा करना (Vaada Karna)",
        example: "She promised to call me later. (उसने बाद में मुझे कॉल करने का वादा किया।)"
      },
      {
        number: 243,
        verb: "Read (रीड)",
        pastSimple: "Read (रेड)",
        pastParticiple: "Read (रेड)",
        presentParticiple: "Reading (रीडिंग)",
        hindiMeaning: "पढ़ना (Padhna)",
        example: "I read an interesting book yesterday. (मैंने कल एक दिलचस्प किताब पढ़ी।)"
      },
      {
        number: 244,
        verb: "Relax (रिलैक्स)",
        pastSimple: "Relaxed (रिलैक्स्ड)",
        pastParticiple: "Relaxed (रिलैक्स्ड)",
        presentParticiple: "Relaxing (रिलैक्सिंग)",
        hindiMeaning: "आराम करना (Aaram Karna)",
        example: "She is relaxing on the couch. (वह सोफे पर आराम कर रही है।)"
      },
      {
        number: 245,
        verb: "Remember (रिमेम्बर)",
        pastSimple: "Remembered (रिमेम्बर्ड)",
        pastParticiple: "Remembered (रिमेम्बर्ड)",
        presentParticiple: "Remembering (रिमेम्बरिंग)",
        hindiMeaning: "याद रखना (Yaad Rakhna)",
        example: "I remembered her birthday. (मुझे उसका जन्मदिन याद रहा।)"
      },
      {
        number: 246,
        verb: "Run (रन)",
        pastSimple: "Ran (रैन)",
        pastParticiple: "Run (रन)",
        presentParticiple: "Running (रनिंग)",
        hindiMeaning: "दौड़ना (Daudna)",
        example: "He ran five kilometers this morning. (उसने आज सुबह पाँच किलोमीटर दौड़ लगाई।)"
      },
      {
        number: 247,
        verb: "Say (से)",
        pastSimple: "Said (सेड)",
        pastParticiple: "Said (सेड)",
        presentParticiple: "Saying (सेइंग)",
        hindiMeaning: "कहना (Kehna)",
        example: "She said she was happy. (उसने कहा कि वह खुश है।)"
      },
      {
        number: 248,
        verb: "See (सी)",
        pastSimple: "Saw (सॉ)",
        pastParticiple: "Seen (सीन)",
        presentParticiple: "Seeing (सीइंग)",
        hindiMeaning: "देखना (Dekhna)",
        example: "I saw a beautiful sunset yesterday. (मैंने कल एक सुंदर सूर्यास्त देखा।)"
      },
      {
        number: 249,
        verb: "Sell (सेल)",
        pastSimple: "Sold (सोल्ड)",
        pastParticiple: "Sold (सोल्ड)",
        presentParticiple: "Selling (सेलिंग)",
        hindiMeaning: "बेचना (Bechna)",
        example: "He sold his old car last week. (उसने पिछले हफ्ते अपनी पुरानी कार बेची।)"
      },
      {
        number: 250,
        verb: "Send (सेंड)",
        pastSimple: "Sent (सेंट)",
        pastParticiple: "Sent (सेंट)",
        presentParticiple: "Sending (सेंडिंग)",
        hindiMeaning: "भेजना (Bhejna)",
        example: "She sent a letter to her friend. (उसने अपने दोस्त को एक पत्र भेजा।)"
      },
      {
        number: 251,
        verb: "Sing (सिंग)",
        pastSimple: "Sang (सैंग)",
        pastParticiple: "Sung (संग)",
        presentParticiple: "Singing (सिंगिंग)",
        hindiMeaning: "गाना (Gana)",
        example: "She sang beautifully at the concert. (उसने कॉन्सर्ट में खूबसूरती से गाया।)"
      },
      {
        number: 252,
        verb: "Sit (सिट)",
        pastSimple: "Sat (सैट)",
        pastParticiple: "Sat (सैट)",
        presentParticiple: "Sitting (सिटिंग)",
        hindiMeaning: "बैठना (Baithna)",
        example: "She sat on the chair. (वह कुर्सी पर बैठ गई।)"
      },
      {
        number: 253,
        verb: "Sleep (स्लीप)",
        pastSimple: "Slept (स्लेपट)",
        pastParticiple: "Slept (स्लेपट)",
        presentParticiple: "Sleeping (स्लीपिंग)",
        hindiMeaning: "सोना (Sona)",
        example: "He slept for eight hours. (वह आठ घंटे तक सोया।)"
      },
      {
        number: 254,
        verb: "Speak (स्पीक)",
        pastSimple: "Spoke (स्पोक)",
        pastParticiple: "Spoken (स्पोकन)",
        presentParticiple: "Speaking (स्पीकिंग)",
        hindiMeaning: "बोलना (Bolna)",
        example: "She spoke clearly during the meeting. (उसने बैठक के दौरान स्पष्ट रूप से बोला।)"
      },
      {
        number: 255,
        verb: "Spend (स्पेंड)",
        pastSimple: "Spent (स्पेंट)",
        pastParticiple: "Spent (स्पेंट)",
        presentParticiple: "Spending (स्पेंडिंग)",
        hindiMeaning: "खर्च करना (Kharch Karna)",
        example: "He spent all his savings on the trip. (उसने अपनी सारी बचत यात्रा पर खर्च कर दी।)"
      },
      {
        number: 256,
        verb: "Stand (स्टैंड)",
        pastSimple: "Stood (स्टूड)",
        pastParticiple: "Stood (स्टूड)",
        presentParticiple: "Standing (स्टैंडिंग)",
        hindiMeaning: "खड़ा होना (Khada Hona)",
        example: "She stood by the window. (वह खिड़की के पास खड़ी थी।)"
      },
      {
        number: 257,
        verb: "Start (स्टार्ट)",
        pastSimple: "Started (स्टार्टेड)",
        pastParticiple: "Started (स्टार्टेड)",
        presentParticiple: "Starting (स्टार्टिंग)",
        hindiMeaning: "शुरू करना (Shuru Karna)",
        example: "They started the project last week. (उन्होंने पिछले हफ्ते परियोजना शुरू की।)"
      },
      {
        number: 258,
        verb: "Study (स्टडी)",
        pastSimple: "Studied (स्टडीड)",
        pastParticiple: "Studied (स्टडीड)",
        presentParticiple: "Studying (स्टडीइंग)",
        hindiMeaning: "पढ़ाई करना (Padhai Karna)",
        example: "She studied all night for the exam. (उसने परीक्षा के लिए पूरी रात पढ़ाई की।)"
      },
      {
        number: 259,
        verb: "Swim (स्विम)",
        pastSimple: "Swam (स्वैम)",
        pastParticiple: "Swum (स्वम)",
        presentParticiple: "Swimming (स्विमिंग)",
        hindiMeaning: "तैरना (Tairna)",
        example: "He swam across the river. (उसने नदी को तैरकर पार किया।)"
      },
      {
        number: 260,
        verb: "Take (टेक)",
        pastSimple: "Took (टुक)",
        pastParticiple: "Taken (टेकन)",
        presentParticiple: "Taking (टेकिंग)",
        hindiMeaning: "लेना (Lena)",
        example: "She took the book from the table. (उसने मेज से किताब उठाई।)"
      },
      {
        number: 261,
        verb: "Talk (टॉक)",
        pastSimple: "Talked (टॉक्ड)",
        pastParticiple: "Talked (टॉक्ड)",
        presentParticiple: "Talking (टॉकिंग)",
        hindiMeaning: "बात करना (Baat Karna)",
        example: "They talked for hours about the project. (उन्होंने परियोजना के बारे में घंटों तक बात की।)"
      },
      {
        number: 262,
        verb: "Teach (टीच)",
        pastSimple: "Taught (टॉट)",
        pastParticiple: "Taught (टॉट)",
        presentParticiple: "Teaching (टीचिंग)",
        hindiMeaning: "पढ़ाना (Padhana)",
        example: "He taught mathematics at the university. (उन्होंने विश्वविद्यालय में गणित पढ़ाया।)"
      },
      {
        number: 263,
        verb: "Tell (टेल)",
        pastSimple: "Told (टोल्ड)",
        pastParticiple: "Told (टोल्ड)",
        presentParticiple: "Telling (टेलिंग)",
        hindiMeaning: "कहना (Kehna)",
        example: "She told me a funny story. (उसने मुझे एक मजेदार कहानी सुनाई।)"
      },
      {
        number: 264,
        verb: "Think (थिंक)",
        pastSimple: "Thought (थॉट)",
        pastParticiple: "Thought (थॉट)",
        presentParticiple: "Thinking (थिंकिंग)",
        hindiMeaning: "सोचना (Sochna)",
        example: "I thought about the problem all day. (मैंने पूरे दिन समस्या के बारे में सोचा।)"
      },
      {
        number: 265,
        verb: "Throw (थ्रो)",
        pastSimple: "Threw (थ्रू)",
        pastParticiple: "Thrown (थ्रोन)",
        presentParticiple: "Throwing (थ्रोइंग)",
        hindiMeaning: "फेंकना (Fenkna)",
        example: "He threw the ball to his friend. (उसने गेंद को अपने दोस्त की ओर फेंका।)"
      },
      {
        number: 266,
        verb: "Try (ट्राय)",
        pastSimple: "Tried (ट्रायड)",
        pastParticiple: "Tried (ट्रायड)",
        presentParticiple: "Trying (ट्रायिंग)",
        hindiMeaning: "कोशिश करना (Koshish Karna)",
        example: "She tried her best to win. (उसने जीतने के लिए अपनी पूरी कोशिश की।)"
      },
      {
        number: 267,
        verb: "Understand (अंडरस्टैंड)",
        pastSimple: "Understood (अंडरस्टूड)",
        pastParticiple: "Understood (अंडरस्टूड)",
        presentParticiple: "Understanding (अंडरस्टैंडिंग)",
        hindiMeaning: "समझना (Samajhna)",
        example: "He understood the instructions clearly. (उसने निर्देशों को स्पष्ट रूप से समझा।)"
      },
      {
        number: 268,
        verb: "Wait (वेट)",
        pastSimple: "Waited (वेटेड)",
        pastParticiple: "Waited (वेटेड)",
        presentParticiple: "Waiting (वेटिंग)",
        hindiMeaning: "प्रतीक्षा करना (Pratiksha Karna)",
        example: "We waited for the bus at the stop. (हम बस स्टॉप पर बस की प्रतीक्षा कर रहे थे।)"
      },
      {
        number: 269,
        verb: "Walk (वॉक)",
        pastSimple: "Walked (वॉक्ड)",
        pastParticiple: "Walked (वॉक्ड)",
        presentParticiple: "Walking (वॉकिंग)",
        hindiMeaning: "चलना (Chalna)",
        example: "She walked to the park in the morning. (वह सुबह पार्क तक चली।)"
      },
      {
        number: 270,
        verb: "Want (वांट)",
        pastSimple: "Wanted (वांटेड)",
        pastParticiple: "Wanted (वांटेड)",
        presentParticiple: "Wanting (वांटिंग)",
        hindiMeaning: "चाहना (Chahna)",
        example: "He wanted to buy a new car. (वह एक नई कार खरीदना चाहता था।)"
      }
  ];